baseURL = "/"
languageCode = 'en-us'
title = 'Ouifi.Dev'
theme = "terminal"

[params]
  author = 'Ouifi'
  themeColor = "blue"
  readingTime = true
  custom_css = ["css/custom.css"]
  centerTheme = true
  showLastUpdated = true

[languages]
  [languages.en]
    languageName = "English"
    title = "OUIFI.DEV"
    subtitle = "A blog on technical topics"
  
  [languages.en.params.logo]
      logoText = "OUIFI.DEV"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "inspirations"
      name = "Inspirations"
      url = "/inspirations"

[logo]
  logoText = "OUIFI.DEV"